# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Templates for generating Agent Skills (SKILL.md, lib/, runtime/, scripts/, references/)."""

SKILL_MD_TEMPLATE = """---
name: {skill_name}
description: {description}
---

# {skill_name_title} Skill

This skill enables managed code-generating agents to dynamically construct, validate, and emit A2UI user interface components to a webview runtime using available component catalogs and function bindings.

---

## 1. When to Activate

Activate this skill whenever:
- The user requests a visual UI output (cards, forms, tables, dashboards, lists, or interactive widgets).
- A response requires presenting structured data or interactive components (e.g. flight itineraries, product listings, checkout flows).

---

## 2. Available Catalogs & Components

{catalog_documentation}

---

## 3. How to Generate & Render UI Code

### Step 1: Write Code using `lib/builder`
Import the generated component helpers from `lib/builder` and assemble your UI tree:

```python
from lib.builder import Card, Text, Button, Container
from lib.emitter import emit_ui

# Construct UI components
ui = Card(
    title=Text("Title"),
    children=[
        Text("Description text here"),
        Button("Action", action_id="on_submit_action")
    ]
)

# Emit payload to webview
emit_ui(ui)
```

### Step 2: Validate Payload (Optional Self-Test)
Before outputting code, you may execute local validation:
```bash
python3 scripts/validate_ui.py --code-file my_ui_script.py
```

### Step 3: References
Look at the files in `references/` for canonical code examples.
"""

SKILL_MD_JS_TEMPLATE = """---
name: {skill_name}
description: {description}
---

# {skill_name_title} Skill (JavaScript Target)

This skill enables managed code-generating agents to dynamically construct, validate, and emit A2UI user interface components directly inside JavaScript webview runtimes.

---

## 1. When to Activate

Activate this skill whenever:
- The user requests a visual UI output in a webview client renderer.
- A response requires presenting structured data or interactive components (e.g. flight itineraries, product listings, checkout flows).

---

## 2. Available Catalogs & Components

{catalog_documentation}

---

## 3. How to Generate & Render JavaScript UI Code

### Step 1: Write JavaScript using `lib/builder.js`
Import the generated component builders from `lib/builder.js` and assemble your UI tree:

```javascript
import {{ Card, Text, Button }} from './lib/builder.js';
import {{ updateComponents, updateDataModel }} from './lib/emitter.js';

// Construct UI components
const ui = new Card({{
    title: "Title",
    children: [
        new Text({{ text: "Description text here" }}),
        new Button({{ label: "Action", action_id: "on_submit_action" }})
    ]
}});

// Emit payload to webview
updateComponents(ui);
```

### Step 2: References
Look at the files in `references/` for canonical JavaScript code examples.
"""

BUILDER_LIB_TEMPLATE = """# Auto-generated A2UI Component Builder Helper DSL
# Do not edit manually. Generated by a2ui_agent.skill_generator.

import json
from typing import Any, Dict, List, Optional, Union


class Component:
    \"\"\"Base class for A2UI components.\"\"\"

    def __init__(self, component_type: str, props: Optional[Dict[str, Any]] = None):
        self.component_type = component_type
        self.props = props or {{}}

    def to_dict(self) -> Dict[str, Any]:
        result = {{"type": self.component_type}}
        for key, value in self.props.items():
            if value is not None:
                if isinstance(value, Component):
                    result[key] = value.to_dict()
                elif isinstance(value, list):
                    result[key] = [v.to_dict() if isinstance(v, Component) else v for v in value]
                elif isinstance(value, dict):
                    result[key] = {{k: v.to_dict() if isinstance(v, Component) else v for k, v in value.items()}}
                else:
                    result[key] = value
        return result

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


{component_classes}
"""

BUILDER_LIB_JS_TEMPLATE = """// Auto-generated A2UI Component Builder Helper DSL (JavaScript)
// Generated by a2ui_agent.skill_generator.

export class Component {{
  constructor(componentType, props = {{}}) {{
    this.type = componentType;
    Object.assign(this, props);
    if (typeof console !== "undefined" && typeof console.debug === "function") {{
      console.debug("[A2UI Builder] Created Component:", componentType, props);
    }}
  }}

  toDict() {{
    const result = {{ type: this.type }};
    for (const [key, value] of Object.entries(this)) {{
      if (key !== "type" && value !== undefined && value !== null) {{
        if (value instanceof Component) {{
          result[key] = value.toDict();
        }} else if (Array.isArray(value)) {{
          result[key] = value.map(v => v instanceof Component ? v.toDict() : v);
        }} else {{
          result[key] = value;
        }}
      }}
    }}
    return result;
  }}
}}

{component_classes}
"""

EMITTER_LIB_TEMPLATE = """# Auto-generated A2UI Emitter Helper
# Emits A2UI JSON messages to stdout or local webview bridge adapter.

import json
import sys
from typing import Any, Dict, Union


def emit_ui(payload: Union[Dict[str, Any], Any], surface_id: str = "main") -> None:
    \"\"\"Emits an A2UI message payload to the client webview renderer.\"\"\"
    if hasattr(payload, "to_dict"):
        data = payload.to_dict()
    elif isinstance(payload, dict):
        data = payload
    else:
        raise TypeError(f"Cannot emit payload of type {type(payload)}")

    message = {
        "version": "0.9",
        "surface_id": surface_id,
        "payload": data
    }
    
    formatted_json = json.dumps(message)
    # Output formatted message delimited by A2UI markers for webview capture
    print("---A2UI_START---")
    print(formatted_json)
    print("---A2UI_END---")
    sys.stdout.flush()
"""

EMITTER_LIB_JS_TEMPLATE = """// Auto-generated A2UI JavaScript Emitter Helper

export function flattenToA2UIGraph(payload) {
  let counter = 0;
  const components = {};

  function walk(node) {
    if (node == null || node === false || node === true) return null;
    const data = (node && typeof node.toDict === "function") ? node.toDict() : node;
    if (typeof data !== "object") return null;

    const id = data.id || ('n' + (++counter));
    const compType = data.type || data.component || "Container";
    
    const props = {};
    const childNodes = [];

    for (const [k, v] of Object.entries(data)) {
      if (k === 'type' || k === 'component' || k === 'id') continue;
      if (k === 'children' && Array.isArray(v)) {
        for (const child of v) {
          if (child && typeof child === 'object') {
            const childId = walk(child);
            if (childId) childNodes.push(childId);
          }
        }
      } else {
        props[k] = v;
      }
    }

    const c = { component: compType, properties: props };
    if (childNodes.length > 0) c.children = childNodes;
    components[id] = c;
    return id;
  }

  const rootId = walk(payload);
  return { root: rootId, components };
}

function emitRaw(message, eventName, eventData) {
  const formattedJson = JSON.stringify(message);
  console.log("---A2UI_START---");
  console.log(formattedJson);
  console.log("---A2UI_END---");

  if (typeof console !== "undefined" && typeof console.info === "function") {
    console.info("%c[A2UI Emitter]%c Action: " + message.action + " (surface: " + message.surface_id + ")", "color: #3b82f6; font-weight: bold;", "color: inherit;", message);
  }

  if (typeof globalThis !== "undefined" && typeof globalThis.emit === "function") {
    globalThis.emit(eventName, eventData);
  } else if (typeof window !== "undefined") {
    window.postMessage({ type: "A2UI_RENDER", eventName, data: message }, "*");
  }
}

// 1. ui.createSurface
export function createSurface(surfaceId = "main", targetContainer = null) {
  const message = {
    version: "0.9",
    action: "ui.createSurface",
    surface_id: surfaceId,
    target_container: targetContainer
  };
  emitRaw(message, 'ui.createSurface', { surfaceId, targetContainer });
}

// 2. ui.updateComponents
export function updateComponents(payload, surfaceId = "main", options = {}) {
  const data = (payload && typeof payload.toDict === "function") ? payload.toDict() : payload;
  const graph = options.flatGraph ? flattenToA2UIGraph(data) : null;
  const message = {
    version: "0.9",
    action: "ui.updateComponents",
    surface_id: surfaceId,
    payload: graph || data
  };
  emitRaw(message, 'ui.updateComponents', { surfaceId, ...(graph || { payload: data }) });
}

// Alias emitUI to updateComponents for convenience
export const emitUI = updateComponents;

// 3. ui.updateDataModel
export function updateDataModel(pathOrData, value = null, surfaceId = "main") {
  const payload = (typeof pathOrData === "string") 
    ? { path: pathOrData, value } 
    : pathOrData;

  const message = {
    version: "0.9",
    action: "ui.updateDataModel",
    surface_id: surfaceId,
    payload
  };
  emitRaw(message, 'ui.updateDataModel', { surfaceId, ...payload });
}

// 4. ui.deleteSurface
export function deleteSurface(surfaceId = "main") {
  const message = {
    version: "0.9",
    action: "ui.deleteSurface",
    surface_id: surfaceId
  };
  emitRaw(message, 'ui.deleteSurface', { surfaceId });
}
"""

VALIDATOR_LIB_TEMPLATE = """# Auto-generated A2UI Payload Validator Helper

import json
from typing import Any, Dict, List, Tuple


def validate_payload(data: Dict[str, Any]) -> Tuple[bool, List[str]]:
    \"\"\"Validates basic structure of an A2UI payload dict.\"\"\"
    errors = []
    if not isinstance(data, dict):
        return False, ["Payload must be a dictionary"]
    
    if "type" not in data and "components" not in data and "version" not in data:
        errors.append("Payload missing component type or components list")
        
    return len(errors) == 0, errors
"""

RUNTIME_BRIDGE_TEMPLATE = """# Auto-generated A2UI Runtime Webview Bridge Adapter
# Connects code execution outputs to local webview renderers.

import json
import re
from typing import Any, Dict, List, Optional


class WebviewBridge:
    \"\"\"Parses stdout streams for A2UI messages and bridges to webview renderer.\"\"\"

    @staticmethod
    def parse_stream(stdout_text: str) -> List[Dict[str, Any]]:
        messages = []
        pattern = r"---A2UI_START---\s*(.*?)\s*---A2UI_END---"
        matches = re.findall(pattern, stdout_text, re.DOTALL)
        for raw in matches:
            try:
                messages.append(json.loads(raw.strip()))
            except json.JSONDecodeError:
                pass
        return messages
"""

RUNTIME_BRIDGE_JS_TEMPLATE = """// Auto-generated A2UI Runtime Webview Bridge Adapter (JavaScript)
// Connects stdout/event streams to local webview renderers.

export class WebviewBridge {
  static parseStream(stdoutText) {
    const messages = [];
    const pattern = /---A2UI_START---\\s*([\\s\\S]*?)\\s*---A2UI_END---/g;
    let match;
    while ((match = pattern.exec(stdoutText)) !== null) {
      try {
        messages.push(JSON.parse(match[1].trim()));
      } catch (e) {
        // Ignore parse errors
      }
    }
    return messages;
  }
}
"""

VALIDATE_UI_SCRIPT_TEMPLATE = """#!/usr/bin/env python3
# CLI tool for verifying generated A2UI script execution and payloads

import argparse
import sys
import subprocess
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Validate A2UI UI script output")
    parser.add_argument("--code-file", required=True, help="Path to Python script to test")
    args = parser.parse_args()

    file_path = Path(args.code_file)
    if not file_path.exists():
        print(f"Error: Code file {file_path} does not exist.")
        sys.exit(1)

    result = subprocess.run([sys.executable, str(file_path)], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Script Execution Failed:\\n{result.stderr}")
        sys.exit(result.returncode)

    if "---A2UI_START---" not in result.stdout:
        print("Warning: Script executed successfully but did not emit ---A2UI_START--- marker.")
        sys.exit(1)

    print("Success: UI script executed and emitted valid A2UI message bounds.")


if __name__ == "__main__":
    main()
"""

VALIDATE_UI_SCRIPT_JS_TEMPLATE = """#!/usr/bin/env node
// CLI tool for verifying generated JavaScript A2UI script execution and payloads

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const args = process.argv.slice(2);
const fileIndex = args.indexOf('--code-file');

if (fileIndex === -1 || fileIndex + 1 >= args.length) {
  console.error("Usage: node validate_ui.js --code-file <path_to_js_file>");
  process.exit(1);
}

const filePath = path.resolve(args[fileIndex + 1]);
if (!fs.existsSync(filePath)) {
  console.error(`Error: Code file ${filePath} does not exist.`);
  process.exit(1);
}

try {
  const stdout = execSync(`node ${filePath}`, { encoding: 'utf8' });
  if (!stdout.includes('---A2UI_START---')) {
    console.error("Warning: Script executed but did not emit ---A2UI_START--- marker.");
    process.exit(1);
  }
  console.log("Success: JS UI script executed and emitted valid A2UI message bounds.");
} catch (err) {
  console.error("Script Execution Failed:", err.message);
  process.exit(1);
}
"""

META_SKILL_MD_TEMPLATE = """---
name: a2ui-create-render-skill
description: Meta-Skill for creating application-specific A2UI render-ui skills for managed agents.
---

# A2UI Create Render-UI Skill Meta-Skill

This skill provides step-by-step instructions for AI Managed Agents (Antigravity, Codex, Cloudflare Code Mode) on how to generate custom `.agents/skills/<skill-name>/` skills using catalog schemas and example UI payloads.

---

## Instructions for Agent

1. **Locate Catalogs & Examples**:
   - Search the workspace for catalog definition files (`catalog.json`, `components.json`, or Pydantic models).
   - Locate any example A2UI JSON payload files in the repository.

2. **Execute SDK Generator Command**:
   Run the `a2ui` skill generator CLI command in the workspace terminal:

   ```bash
   python3 -m a2ui.skill_generator \\
     --name {skill_name} \\
     --catalog {catalog_path} \\
     --target-language {target_language} \\
     --output .agents/skills/{skill_name}
   ```

3. **Verify Created Skill**:
   - Ensure `.agents/skills/{skill_name}/SKILL.md` exists and contains catalog component specifications.
   - Verify that `lib/builder.js` (or `lib/builder.py`) and `references/` code snippets were generated.
"""
